name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  My MLOps Job:
    runs-on: ubuntu-latest
    steps:
      - name: hello 
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      
