on: push

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
    - run: |
        import os
        print(len(os.getenv('MY_VAR')))
      shell: python3
      env:
        MY_VAR: ${{ secrets.MY_SECRET }}
        
